include: package:very_good_analysis/analysis_options.2.4.0.yaml

linter:
  rules:
    public_member_api_docs: true
    package_api_docs: true
    # Doesn't play well with "_MyWidgetState"-style Flutter State classes.
    library_private_types_in_public_api: false
