name: cupertino_plus
description: A collection of pixel-perfect iOS-styled components and properties
  for Flutter, following the official guidelines.
version: 0.0.1-dev.1
homepage: https://github.com/cupertino-plus/cupertino_plus/tree/main/packages/cupertino_plus
repository: https://github.com/cupertino-plus/cupertino_plus/tree/main/packages/cupertino_plus

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  matcher: ^0.12.10
  very_good_analysis: ^2.4.0
